spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3901/base1
    username: sanus
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update

file:
  dir: C:/workspace/spring/base1/src/main/resources/static/images/
